# Render Blueprint Specification
# https://render.com/docs/blueprint-spec

version: "1"

services:
  - type: web
    name: image-classifier-web-app
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
